"""
Benchmark runner for Shiori compressors.

Purpose:
    Run each corpus sample through the appropriate compressor and return
    structured results. No API keys, no network calls, no side effects.

Inputs / Outputs:
    Input:  CORPUS dict from corpus.py
    Output: list[BenchResult] — one entry per (content_type, compressor) pair

Compressor assignment:
    json_array   → JsonCompressor  (content-type-aware)
    log_lines    → LosslessCompressor
    stack_trace  → LosslessCompressor
    python_code  → LosslessCompressor
    plain_prose  → LosslessCompressor

Invariant: results are deterministic — same corpus → same numbers every run.
"""
from __future__ import annotations

from dataclasses import dataclass

from shiori.bench.corpus import CORPUS
from shiori.compressors.ast_compressor import AstCompressor
from shiori.compressors.json_compressor import JsonCompressor
from shiori.compressors.lossless import LosslessCompressor

_COMPRESSORS = {
    "json_array": JsonCompressor(),
    "log_lines": LosslessCompressor(),
    "stack_trace": LosslessCompressor(),
    "python_code": AstCompressor(),
    "plain_prose": LosslessCompressor(),
}


@dataclass(frozen=True)
class BenchResult:
    content_type: str
    compressor_name: str
    original_tokens: int
    compressed_tokens: int

    @property
    def saving_pct(self) -> float:
        if self.original_tokens == 0:
            return 0.0
        return (1.0 - self.compressed_tokens / self.original_tokens) * 100.0


def run_bench() -> list[BenchResult]:
    """Run all corpus samples through their assigned compressor."""
    results: list[BenchResult] = []
    for content_type, text in CORPUS.items():
        compressor = _COMPRESSORS[content_type]
        cr = compressor.compress(text)
        results.append(BenchResult(
            content_type=content_type,
            compressor_name=compressor.name,
            original_tokens=cr.original_tokens,
            compressed_tokens=cr.compressed_tokens,
        ))
    return results


def format_table(results: list[BenchResult]) -> str:
    """Return a plain-text table for CLI output."""
    header = f"{'content_type':<20} {'compressor':<12} {'original':>10} {'compressed':>10} {'saving':>8}"
    sep = "-" * len(header)
    rows = [header, sep]
    for r in results:
        rows.append(
            f"{r.content_type:<20} {r.compressor_name:<12} "
            f"{r.original_tokens:>10} {r.compressed_tokens:>10} "
            f"{r.saving_pct:>7.1f}%"
        )
    return "\n".join(rows)


def format_markdown(results: list[BenchResult]) -> str:
    """Return a Markdown table for docs/benchmarks.md."""
    lines = [
        "# Shiori compression benchmarks",
        "",
        "Generated by `python -m shiori.bench --save`. Do not edit manually.",
        "",
        "| content_type | compressor | original tokens | compressed tokens | saving |",
        "|---|---|---:|---:|---:|",
    ]
    for r in results:
        lines.append(
            f"| {r.content_type} | {r.compressor_name} "
            f"| {r.original_tokens} | {r.compressed_tokens} | {r.saving_pct:.1f}% |"
        )
    return "\n".join(lines) + "\n"
